# SPDX-License-Identifier: Apache-2.0
# Code authors: Vijay Erramilli and Codex
**
!dist/
!dist/docker/
!dist/docker/otelcol-genai-sketches
!examples/
!examples/collector/
!examples/collector/Dockerfile
!examples/collector/config.yaml
