# SPDX-License-Identifier: Apache-2.0
# Code authors: Vijay Erramilli and Codex
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: otelcol-genai-sketches
    static_configs:
      - targets: ["collector:8889"]
