# SPDX-License-Identifier: Apache-2.0
# Code authors: Vijay Erramilli and Codex
apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
